### ISSUE TITLE
change java version to python ?

### ISSUE THREAD

**Issue by xx-zhang** [datthinh1801/cicflowmeter#2]
why not using `tshark` ?

**Comment by datthinh1801** [comment]
Originally, I wanted to integrate CICFlowmeter into my Python project so I found [this repo](https://gitlab.com/hieulw/cicflowmeter) and customized it a little bit to fit my needs.

As far as I know, `tcpdump` is the most underlying network sniffing tool, whereas `tshark`  is a tool to unpack packets captured from such sniffing tools like `tcpdump`, so Scapy uses `tcpdump` to sniff packets and they unpack those packets in their own way.

Also, my project was complete and this repository is not actively maintained now. If you want to use `tshark` instead of Scapy, feel free to fork this repository and customize the code to fit your needs and interests.
